apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: restic-init-es
  namespace: demo
spec:
  version: "6.3-v1"
  databaseSecret:
    secretName: scheduled-pg-auth
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  init:
    stashSource:
      name: restore-session-name
